### ISSUE TITLE
Need to set proper default config for Length Indicator

### ISSUE THREAD

**Issue by moerazem** [Vardot/varbase_core#1]
The default config that comes with the modules is not correct. 10 and 15 are not good indicators for a good title.

@Natshah Please make it as follows:
- OPTIMUM MINIMUM: 15
- OPTIMUM MAXIMUM: 50
- TOLERANCE: 10

**Comment by Natshah** [comment]
Still, we do need a way to update that in all needed content types. which may go into the targeted modules
We could do a custom cascade hook_form_alter to have a default confg for content types
And then if a content type needed a custom activation or values opt max or min it override the cascade

**Comment by Natshah** [comment]
[#3048206](https://www.drupal.org/project/varbase_core/issues/3048206): Add [Length Indicator] module 8.1.0-rc3
[#3049744](https://www.drupal.org/project/vartheme_admin/issues/3049744): Have the title element go to the end of line, with the Length Indicator and the title should have the same exact width, on all responsive sizes
[#3049760](https://www.drupal.org/project/varbase_blog/issues/3049760): Add [Length Indicator] to the form view config for [Blog post] content type
[#3049761](https://www.drupal.org/project/varbase_faqs/issues/3049761): Add [Length Indicator] to the form view config for [FAQ] content type
[#3049762](https://www.drupal.org/project/varbase_heroslider_media/issues/3049762): Add [Length Indicator] to the form view config for [Hero slider] content type
